apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendj-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opendj-operator
  template:
    metadata:
      labels:
        name: opendj-operator
    spec:
      serviceAccountName: opendj-operator
      containers:
        - name: opendj-operator
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - opendj-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "opendj-operator"
